# Generated by Django 5.2.14 on 2026-06-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('L', 'Lojista'), ('C', 'Cliente')], default='C'),
        ),
    ]
