# Generated by Django 5.2.14 on 2026-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('C', 'Cliente'), ('L', 'Lojista')], default='C'),
        ),
    ]
