# Generated by Django 5.2.14 on 2026-06-12 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('cep', models.CharField(max_length=8)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField()),
                ('neightborhood', models.CharField()),
                ('street', models.CharField()),
                ('number', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
