# Generated by Django 5.2.14 on 2026-06-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_usertype_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='validity',
            new_name='validity_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('L', 'Lojista'), ('C', 'Cliente')], default='C'),
        ),
    ]
