# Generated by Django 5.2.14 on 2026-05-17 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='address',
            name='neightborhood',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
