# Generated by Django 5.2.14 on 2026-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('C', 'Cliente'), ('L', 'Lojista')], default=0),
            preserve_default=False,
        ),
    ]
