# Generated by Django 5.2.14 on 2026-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('L', 'Lojista'), ('C', 'Cliente')], default='L'),
        ),
    ]
