# Generated by Django 5.2.14 on 2026-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.CharField(),
        ),
    ]
