# Generated by Django 5.2.14 on 2026-06-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_contact_support'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_support',
            new_name='contact_support_email',
        ),
    ]
