# Generated by Django 5.2.14 on 2026-06-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_rename_contact_support_contact_support_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
