# Generated by Django 5.2.14 on 2026-06-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_delete_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
