# Generated by Django 5.2.14 on 2026-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_rename_date_created_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
