# Generated by Django 5.2.14 on 2026-06-14 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_alter_review_star_cart_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 14, 20, 20, 14, 445973, tzinfo=datetime.timezone.utc)),
        ),
    ]
