# Generated by Django 5.2.14 on 2026-06-15 04:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_alter_cart_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='variations',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 15, 4, 10, 52, 344435, tzinfo=datetime.timezone.utc)),
        ),
    ]
