# Generated by Django 5.2.14 on 2026-06-15 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_cart_item_variations_alter_cart_date_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='shopkeeper',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 15, 5, 24, 3, 210379, tzinfo=datetime.timezone.utc)),
        ),
    ]
