# Generated by Django 5.2.14 on 2026-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_alter_cart_date_update_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('SEPARATION', 'Separating'), ('SENT', 'Sent'), ('CREATED', 'CREATED / Awaiting Payment'), ('DELIVERED', 'Delivered'), ('PAID', 'Paid'), ('CANCELED', 'Canceled')], default='CREATED'),
        ),
    ]
