# Generated by Django 5.2.14 on 2026-06-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_rename_create_at_orders_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('SEPARATION', 'Separating'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('PAID', 'Paid'), ('CREATED', 'CREATED / Awaiting Payment'), ('CANCELED', 'Canceled')], default='CREATED'),
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.product')),
                ('variations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecommerce.stock')),
            ],
        ),
    ]
