# Generated by Django 5.2.14 on 2026-06-15 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_validity_card_validity_date_and_more'),
        ('ecommerce', '0021_alter_orders_status_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('SENT', 'Sent'), ('CANCELED', 'Canceled'), ('SEPARATION', 'Separating'), ('DELIVERED', 'Delivered'), ('CREATED', 'CREATED / Awaiting Payment')], default='CREATED'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Card', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='card', to='account.card')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ecommerce.orders')),
            ],
        ),
    ]
