# Generated by Django 5.2.14 on 2026-06-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_orders_status_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('SEPARATION', 'Separating'), ('CANCELED', 'Canceled'), ('DELIVERED', 'Delivered'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('CREATED', 'CREATED / Awaiting Payment')], default='CREATED'),
        ),
    ]
