# Generated by Django 5.2.14 on 2026-06-15 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_validity_card_validity_date_and_more'),
        ('ecommerce', '0023_rename_price_orders_total_price_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent'), ('CREATED', 'CREATED / Awaiting Payment'), ('DELIVERED', 'Delivered'), ('PAID', 'Paid'), ('CANCELED', 'Canceled'), ('SEPARATION', 'Separating')], default='CREATED'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card', to='account.card'),
        ),
    ]
